### ISSUE TITLE
docker部署提示获取Emby媒体总列表失败  win下执行就正常

### ISSUE THREAD

**Issue by emcd39** [sleikang/EmbyChineseNameSynchronous#10]
![image](https://user-images.githubusercontent.com/65075014/190541948-0d7328e6-37c9-4149-97de-86ebe84c85fd.png)
docker部署提示获取Emby媒体总列表失败  win下执行就正常 config文件都是一样的

**Comment by lumenofwhy** [comment]
自己进容器内部，先检查下映射是否正确吧

**Comment by DDS-ALL** [comment]
试试看使用host网络

> ![image](https://user-images.githubusercontent.com/65075014/190541948-0d7328e6-37c9-4149-97de-86ebe84c85fd.png) docker部署提示获取Emby媒体总列表失败 win下执行就正常 config文件都是一样的

**Comment by emcd39** [comment]
找到原因了 我给docker挂了个代理all_proxy 然后就出现问题了 但不挂代理又连不上tmdb
