### ISSUE TITLE
多季描述会重复

### ISSUE THREAD

**Issue by Tasle** [sleikang/EmbyChineseNameSynchronous#13]
发现有两个情况
1.一个剧有多季的有时候会只替换第一季
2.比如生死狙击和名校风暴这种，最后一季会和前面一季的描述重复，一模一样

**Comment by sleikang** [comment]
我这边测试是正常的

**Comment by Tasle** [comment]
> 我这边测试是正常的

那我再试试吧 ，谢谢了
