### ISSUE TITLE
尊敬的开发者大大，请问有如何在群晖docker部署的说明吗？

### ISSUE THREAD

**Issue by EliteOtaku** [sleikang/EmbyChineseNameSynchronous#14]
在网上搜了一圈，没有找到，我对命令行操作docker不熟悉，试探了几次都出错了……
在群晖下的docker目录下建立了文件夹EmbyChineseNameSynchronous，然后里面放了/config，里面再放config.yaml，其中按自己的配置修改了下，但log显示如下，不知道哪里弄错了，请开发者大大指点，非常感谢。
![image](https://user-images.githubusercontent.com/29235152/198871772-d5ab9b5d-2df1-43dc-8210-1ca024201160.png)

----------------------------------------

    _____  ____  _   _  ____  

    | ____|/ ___|| \ | |/ ___| 

    |  _| | |    |  \| |\___ \ 

    | |___| |___ | |\  | ___) |

    |_____|\____||_| \_||____/ 

----------------------------------------

以PUID=0，PGID=0的身份启动程序,umask=022

2022-10-30 17:10:04,127	INFO: 开始刷新媒体库元数据

2022-10-30 17:10:04,138	INFO: 获取Emby媒体总列表失败, 异常错误：Invalid URL '/emby/Users//Items?api_key=': No scheme supplied. Perhaps you meant http:///emby/Users//Items?api_key=?

**Comment by sleikang** [comment]
我这边不使用docker不清楚，看日志是未读取到配置文件

**Comment by EliteOtaku** [comment]
> 我这边不使用docker不清楚，看日志是未读取到配置文件

你好，请问config.yaml是放在根目录里面，还是/config呢？

**Comment by sleikang** [comment]
在config下
