### ISSUE TITLE
Connection reset by peer 异常

### ISSUE THREAD

**Issue by chcGolang** [sleikang/EmbyChineseNameSynchronous#6]
部署方式:  docker
使用docker镜像: ddsderek/embychinesenamesynchronous
版本: 1.0.8
错误日志:
![image](https://user-images.githubusercontent.com/41823338/189018666-1514263e-310e-4abe-bbf0-02c24460e8b2.png)

**Comment by sleikang** [comment]
这是连不上媒体服务器与代码无关
