### ISSUE TITLE
项目建议

### ISSUE THREAD

**Issue by lumenofwhy** [sleikang/EmbyChineseNameSynchronous#7]
## 配置文件
使用config.yaml.default文件（每次发布新版本时做出的改动都体现在这个文件），在每次程序启动时判断目录下是否存在config.yaml文件，没有就利用config.yaml.default创建，否则就读取原有config.yaml文件配置内容，填入新的config.yaml文件（使用新config.yaml.default模板），这样就可以在更新时保留旧配置信息。

## 数据库文件
启动时应该判断是否有data.db文件，否则程序启动时会自动创建一个空的data.db影响正常运行，其余思路与上一个建议相同。
👍（程序很实用）

**Comment by sleikang** [comment]
已添加

**Comment by lumenofwhy** [comment]
另外，可以把python依赖都放进requirement.txt文件里
https://zhuanlan.zhihu.com/p/69058584

**Comment by lumenofwhy** [comment]
每次发布新版本时建议还是附带一份最新的config.default.yaml文件，因为覆盖后的config.yaml文件是不带注释的👽，不好对应着条目填写
